######################## default configuration ####################
baseURL = "https://tristanmeyrowski.com/"
summaryLength = "10"
paginate = 6

[outputs]
  home = ["HTML", "RSS", "JSON"]

######################## Languages ####################
defaultContentLanguage = "fr"

[languages]
    [languages.fr]
        title = "Blog en Vf"
        description = "C'est ici pour la meta description"
        weight = 1
        contentDir = "content/fr"
        [languages.fr.menu]

            [[languages.fr.menu.main]]
                name = "A propos"
                url = "/"
                weight = 1

            [[languages.fr.menu.main]]
                name = "Blog"
                url = "blog"
                weight = 2

    [languages.en]
        title = "My blog"
        description = "This is meta description"
        weight = 2
        contentDir = "content/en"
        [languages.en.menu]

            [[languages.en.menu.main]]
                name = "About"
                url = "/"
                weight = 1

            [[languages.en.menu.main]]
                  name = "Blog"
                  url = "blog"
                  weight = 2

############################# Params ##############################
[params]
logo = "images/logo.png"
author = "Tristan Meyrowski"
# Google Analitycs
#googleAnalyticsID = "Your ID"
# copyright
#copyright = "| copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved |"
    # search
    [params.search]
    enable = true

    # cookies
    [params.cookies]
    enable = false
    expire_days = 2

    # social
    [[params.social]]
    title = "github"
    icon = "ti-github"
    link = "#github"

    [[params.social]]
    title = "linkedin"
    icon = "ti-linkedin"
    link = "#linkedin"

    [[params.social]]
    title = "facebook"
    icon = "ti-facebook"
    link = "#facebook"

    [[params.social]]
    title = "twitter"
    icon = "ti-twitter-alt"
    link = "#twitter"

    # plugins
    [params.plugins]

        # CSS Plugins
        [[params.plugins.css]]
        URL = "plugins/bootstrap/bootstrap.min.css"
        [[params.plugins.css]]
        URL = "plugins/slick/slick.css"
        [[params.plugins.css]]
        URL = "plugins/themify-icons/themify-icons.css"

        # JS Plugins
        [[params.plugins.js]]
        URL = "plugins/jQuery/jquery.min.js"
        [[params.plugins.js]]
        URL = "plugins/bootstrap/bootstrap.min.js"
        [[params.plugins.js]]
        URL = "plugins/slick/slick.min.js"
        [[params.plugins.js]]
        URL = "plugins/venobox/venobox.min.js"
        [[params.plugins.js]]
        URL = "plugins/search/fuse.min.js"
        [[params.plugins.js]]
        URL = "plugins/search/mark.js"
        [[params.plugins.js]]
        URL = "plugins/search/search.js"




